### PR TITLE
Update minimap.js

### PR DESCRIPTION
**Pull request by bPCioSubstituteOPfromLastWeek**
Removed ponies.

### CODE REVIEW

**Comment by kekw-420** [comment]
maybe we should at least keep a thank you, they made the script after all

**Comment by kekw-420** [comment]
also i remember about something called git.rip maybe we can use that instead of github? ill look into it

**Comment by bPCioSubstituteOPfromLastWeek** [comment]
They're not the original authors. It's oldfag lore. I kept that part of the credit in, even though the general has a warning against their bait lol.

**Comment by bPCioSubstituteOPfromLastWeek** [comment]
> git.rip

Well, now I'm on a list

image

**Pull request merged**
